generator:
  class: sfDoctrineGenerator
  param:
    model_class:           peanutPage
    theme:                 peanut
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          peanut_page
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:
        display:
          "Content":        [fr, en, peanutSeo]
          "Informations":   [status, author, menu, created_at]

      edit:    ~
      new:     ~
